import dynamic from "next/dynamic";
import Head from "next/head";

const Auth = dynamic(() => import("../containers/auth"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Hallo Sayang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
    </>
  );
}
